name: release
on:
  push:
    branches:
      - 'master'
  pull_request: {}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '15.11.0'

      # Cache node_modules for faster CI runs if the yarn.lock doesn't change change
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Throw an error if the yarn.lock file doesn't match the installed dependencies (rather than updating it in-place, which it does by default locally)
      - name: Install
        run: yarn install --frozen-lockfile --silent

      - name: Typecheck
        run: yarn test:ts

      - name: Tests (Jest)
        run: yarn test:unit

      - name: Test (Cypress)
        run: yarn test:e2e

      - name: Build
        run: yarn build
